apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-finance-me
  labels:
    app: bankapp-finance-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp-finance-me
  template:
    metadata:
      labels:
        app: bankapp-finance-me
    spec:
      containers:
      - name: bankapp-finance
        image: rnavindevops/bankingproject:1.0
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-finance-me
  labels:
    app: bankapp-finance-me
spec:
  selector:
    app: bankapp-finance-me

  type: NodePort
  ports:
  - nodePort: 31032
    port: 8085
    targetPort: 8085
